# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

common: &common
  google_maps_api_key: <%= ENV["GOOGLE_MAPS_API_KEY"] %>
  streak_api_key: <%= ENV["STREAK_API_KEY"] %>

development:
  <<: *common
  secret_key_base: 6d02f9126a44347e07442fddf774b6a434a85b86e23629eab947c9c101b8aa878ad8fe5dadba26a3341f1a16f480068ae5234861cb7b913f526a0e96a21fcc7d

test:
  <<: *common
  secret_key_base: 7690707d9315088014cce0ab1384a190c8d12cabc0a25d54ec937ee961c0fea23794db571bd4ba3e3ca3e6b9d1229ddbced73015510ddf1b8dbe0839881f4011

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *common
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
